version: 0.2

phases:
  install:
    runtime-versions:
        docker: 18     
    commands: 
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      #- yum -y update
      # Taskfile
      #- yum -y install tar gzip
      #- curl -sL https://taskfile.dev/install.sh | sh
      # Enable ECR auth
      - amazon-linux-extras enable docker
      - yum -y install docker amazon-ecr-credential-helper
      - mkdir ~/.docker
      - "echo $'{\n    \"credsStore\": \"ecr-login\"\n}' > ~/.docker/config.json"

  build:
    commands:
      - "docker build -t 237125764297.dkr.ecr.eu-west-1.amazonaws.com/codebuild-images:codebuild."
      - "docker push 237125764297.dkr.ecr.eu-west-1.amazonaws.com/codebuild-images:codebuild"
      - "docker push 237125764297.dkr.ecr.eu-west-1.amazonaws.com/codebuild-images:codebuild"
